// Re-export analysis types needed by generator
export type {
  AnalysisResult,
  ApiEndpoint,
  ArchitectureOverview,
  BusinessLogicAnalysis,
  BusinessRule,
  ChangelogChange,
  ChangelogEntry,
  CommonError,
  ComponentDoc,
  ConfigurationAnalysis,
  ConfigurationItem,
  CrossRepoAnalysis,
  DataModelDoc,
  DomainConcept,
  ErrorCode,
  ErrorHandlingAnalysis,
  Feature,
  FeaturesAnalysis,
  GettingStartedGuide,
  IntegrationPattern,
  MermaidDiagram,
  StaticAnalysis,
  Workflow,
} from "@latent-space-labs/auto-doc-analyzer";
